// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lms-aitools/AiToolStyle1.tsx": () => import("../components/mockups/lms-aitools/AiToolStyle1.tsx"),
  "./components/mockups/lms-aitools/AiToolStyle2.tsx": () => import("../components/mockups/lms-aitools/AiToolStyle2.tsx"),
  "./components/mockups/lms-aitools/AiToolStyle3.tsx": () => import("../components/mockups/lms-aitools/AiToolStyle3.tsx"),
  "./components/mockups/lms-aitools/AiToolStyle4.tsx": () => import("../components/mockups/lms-aitools/AiToolStyle4.tsx"),
  "./components/mockups/lms-cards/CardBordered.tsx": () => import("../components/mockups/lms-cards/CardBordered.tsx"),
  "./components/mockups/lms-cards/CardGlass.tsx": () => import("../components/mockups/lms-cards/CardGlass.tsx"),
  "./components/mockups/lms-cards/CardGradient.tsx": () => import("../components/mockups/lms-cards/CardGradient.tsx"),
  "./components/mockups/lms-cards/CardSolid.tsx": () => import("../components/mockups/lms-cards/CardSolid.tsx"),
  "./components/mockups/lms-courses/CourseStyle1.tsx": () => import("../components/mockups/lms-courses/CourseStyle1.tsx"),
  "./components/mockups/lms-courses/CourseStyle2.tsx": () => import("../components/mockups/lms-courses/CourseStyle2.tsx"),
  "./components/mockups/lms-courses/CourseStyle3.tsx": () => import("../components/mockups/lms-courses/CourseStyle3.tsx"),
  "./components/mockups/lms-courses/CourseStyle4.tsx": () => import("../components/mockups/lms-courses/CourseStyle4.tsx"),
  "./components/mockups/lms-themes/Blue.tsx": () => import("../components/mockups/lms-themes/Blue.tsx"),
  "./components/mockups/lms-themes/Emerald.tsx": () => import("../components/mockups/lms-themes/Emerald.tsx"),
  "./components/mockups/lms-themes/Rose.tsx": () => import("../components/mockups/lms-themes/Rose.tsx"),
  "./components/mockups/lms-themes/Violet.tsx": () => import("../components/mockups/lms-themes/Violet.tsx")
};
