// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/lms-themes/Blue.tsx": () => import("../components/mockups/lms-themes/Blue.tsx"),
  "./components/mockups/lms-themes/Emerald.tsx": () => import("../components/mockups/lms-themes/Emerald.tsx"),
  "./components/mockups/lms-themes/Rose.tsx": () => import("../components/mockups/lms-themes/Rose.tsx"),
  "./components/mockups/lms-themes/Violet.tsx": () => import("../components/mockups/lms-themes/Violet.tsx")
};
